-- Insert Student Data from Handwritten Records
-- This script inserts all students with their payment totals

-- Insert profiles (students)
INSERT INTO profiles (id, email, password_hash, full_name, phone, id_number, date_of_birth, address, avatar_url, created_at, updated_at) VALUES
('student-001', 'faith.wambu.matinda@drivingschool.com', '$2a$10$defaulthash', 'Faith Wambu Matinda', NULL, '11604', NULL, NULL, NULL, datetime('now'), datetime('now')),
('student-002', 'kamau.jane.kamani@drivingschool.com', '$2a$10$defaulthash', 'Kamau Jane Kamani', NULL, '12600', NULL, NULL, NULL, datetime('now'), datetime('now')),
('student-003', 'grace.mwihaki.kamani@drivingschool.com', '$2a$10$defaulthash', 'Grace Mwihaki Kamani', NULL, '12600', NULL, NULL, NULL, datetime('now'), datetime('now')),
('student-004', 'bweyeire.njoka@drivingschool.com', '$2a$10$defaulthash', 'Bweyeire Njoka', NULL, '12600', NULL, NULL, NULL, datetime('now'), datetime('now')),
('student-005', 'roseline.wanjiku@drivingschool.com', '$2a$10$defaulthash', 'Roseline Wanjiku', NULL, '12600', NULL, NULL, NULL, datetime('now'), datetime('now')),
('student-006', 'veronica.olive.onditi@drivingschool.com', '$2a$10$defaulthash', 'Veronica Olive Onditi', NULL, '9360', NULL, NULL, NULL, datetime('now'), datetime('now')),
('student-007', 'fridah.mutiga@drivingschool.com', '$2a$10$defaulthash', 'Fridah Mutiga', NULL, '12600', NULL, NULL, NULL, datetime('now'), datetime('now')),
('student-008', 'esther.wambui@drivingschool.com', '$2a$10$defaulthash', 'Esther Wambui', NULL, '12600', NULL, NULL, NULL, datetime('now'), datetime('now')),
('student-009', 'antony.mwangi.cimaini@drivingschool.com', '$2a$10$defaulthash', 'Antony Mwangi Cimaini', NULL, '8700', NULL, NULL, NULL, datetime('now'), datetime('now')),
('student-010', 'charles.mwangi.rigiti@drivingschool.com', '$2a$10$defaulthash', 'Charles Mwangi Rigiti', NULL, '', NULL, NULL, NULL, datetime('now'), datetime('now')),
('student-011', 'hamisi.platini.kamau@drivingschool.com', '$2a$10$defaulthash', 'Hamisi Platini Kamau', NULL, '12600', NULL, NULL, NULL, datetime('now'), datetime('now')),
('student-012', 'oscan.kalu@drivingschool.com', '$2a$10$defaulthash', 'Oscan Kalu', NULL, '9360', NULL, NULL, NULL, datetime('now'), datetime('now')),
('student-013', 'jane.fauzi.wambua@drivingschool.com', '$2a$10$defaulthash', 'Jane Fauzi Wambua', NULL, '', NULL, NULL, NULL, datetime('now'), datetime('now')),
('student-014', 'chrispin.ochieng@drivingschool.com', '$2a$10$defaulthash', 'Chrispin Ochieng', NULL, '', NULL, NULL, NULL, datetime('now'), datetime('now')),
('student-015', 'christine.wambui@drivingschool.com', '$2a$10$defaulthash', 'Christine Wambui', NULL, '', NULL, NULL, NULL, datetime('now'), datetime('now')),
('student-016', 'jemimah.kamilia@drivingschool.com', '$2a$10$defaulthash', 'Jemimah Kamilia', NULL, '', NULL, NULL, NULL, datetime('now'), datetime('now')),
('student-017', 'catherine.wanjiku@drivingschool.com', '$2a$10$defaulthash', 'Catherine Wanjiku', NULL, '8700', NULL, NULL, NULL, datetime('now'), datetime('now')),
('student-018', 'nicholas.kipkoech@drivingschool.com', '$2a$10$defaulthash', 'Nicholas Kipkoech', NULL, '', NULL, NULL, NULL, datetime('now'), datetime('now')),
('student-019', 'moses.juma.kinyua@drivingschool.com', '$2a$10$defaulthash', 'Moses Juma Kinyua', NULL, '', NULL, NULL, NULL, datetime('now'), datetime('now')),
('student-020', 'teresiah.mwiti.david@drivingschool.com', '$2a$10$defaulthash', 'Teresiah Mwiti David', NULL, '', NULL, NULL, NULL, datetime('now'), datetime('now')),
('student-021', 'dennis.mwangi.wanjiku@drivingschool.com', '$2a$10$defaulthash', 'Dennis Mwangi Wanjiku', NULL, '', NULL, NULL, NULL, datetime('now'), datetime('now')),
('student-022', 'liness.muigi@drivingschool.com', '$2a$10$defaulthash', 'Liness Muigi', NULL, '', NULL, NULL, NULL, datetime('now'), datetime('now')),
('student-023', 'kamiunga.wambui@drivingschool.com', '$2a$10$defaulthash', 'Kamiunga Wambui', NULL, '', NULL, NULL, NULL, datetime('now'), datetime('now')),
('student-024', 'james.mwangi@drivingschool.com', '$2a$10$defaulthash', 'James Mwangi', NULL, '', NULL, NULL, NULL, datetime('now'), datetime('now')),
('student-025', 'collins.kiprotich@drivingschool.com', '$2a$10$defaulthash', 'Collins Kiprotich', NULL, '', NULL, NULL, NULL, datetime('now'), datetime('now')),
('student-026', 'ann.mwangi.wanjiru@drivingschool.com', '$2a$10$defaulthash', 'Ann Mwangi Wanjiru', NULL, '', NULL, NULL, NULL, datetime('now'), datetime('now')),
('student-027', 'romina.ochieng@drivingschool.com', '$2a$10$defaulthash', 'Romina Ochieng', NULL, '', NULL, NULL, NULL, datetime('now'), datetime('now')),
('student-028', 'fridah.kaminto@drivingschool.com', '$2a$10$defaulthash', 'Fridah Kaminto', NULL, '', NULL, NULL, NULL, datetime('now'), datetime('now')),
('student-029', 'bernadine.wanjiku.mwangi@drivingschool.com', '$2a$10$defaulthash', 'Bernadine Wanjiku Mwangi', NULL, '', NULL, NULL, NULL, datetime('now'), datetime('now')),
('student-030', 'jane.esau.wambui@drivingschool.com', '$2a$10$defaulthash', 'Jane Esau Wambui', NULL, '', NULL, NULL, NULL, datetime('now'), datetime('now'));

-- Insert user roles (all as students)
INSERT INTO user_roles (id, user_id, role, created_at) VALUES
('role-001', 'student-001', 'student', datetime('now')),
('role-002', 'student-002', 'student', datetime('now')),
('role-003', 'student-003', 'student', datetime('now')),
('role-004', 'student-004', 'student', datetime('now')),
('role-005', 'student-005', 'student', datetime('now')),
('role-006', 'student-006', 'student', datetime('now')),
('role-007', 'student-007', 'student', datetime('now')),
('role-008', 'student-008', 'student', datetime('now')),
('role-009', 'student-009', 'student', datetime('now')),
('role-010', 'student-010', 'student', datetime('now')),
('role-011', 'student-011', 'student', datetime('now')),
('role-012', 'student-012', 'student', datetime('now')),
('role-013', 'student-013', 'student', datetime('now')),
('role-014', 'student-014', 'student', datetime('now')),
('role-015', 'student-015', 'student', datetime('now')),
('role-016', 'student-016', 'student', datetime('now')),
('role-017', 'student-017', 'student', datetime('now')),
('role-018', 'student-018', 'student', datetime('now')),
('role-019', 'student-019', 'student', datetime('now')),
('role-020', 'student-020', 'student', datetime('now')),
('role-021', 'student-021', 'student', datetime('now')),
('role-022', 'student-022', 'student', datetime('now')),
('role-023', 'student-023', 'student', datetime('now')),
('role-024', 'student-024', 'student', datetime('now')),
('role-025', 'student-025', 'student', datetime('now')),
('role-026', 'student-026', 'student', datetime('now')),
('role-027', 'student-027', 'student', datetime('now')),
('role-028', 'student-028', 'student', datetime('now')),
('role-029', 'student-029', 'student', datetime('now')),
('role-030', 'student-030', 'student', datetime('now'));

-- Insert enrollments
INSERT INTO enrollments (id, user_id, course_id, status, enrolled_at) VALUES
('enroll-001', 'student-001', 'class-b', 'completed', datetime('now')),
('enroll-002', 'student-002', 'class-b', 'active', datetime('now')),
('enroll-003', 'student-003', 'class-b', 'active', datetime('now')),
('enroll-004', 'student-004', 'class-b', 'active', datetime('now')),
('enroll-005', 'student-005', 'class-b', 'active', datetime('now')),
('enroll-006', 'student-006', 'class-a', 'active', datetime('now')),
('enroll-007', 'student-007', 'class-b', 'active', datetime('now')),
('enroll-008', 'student-008', 'class-b', 'active', datetime('now')),
('enroll-009', 'student-009', 'class-b-half', 'active', datetime('now')),
('enroll-010', 'student-010', 'class-b-half', 'completed', datetime('now')),
('enroll-011', 'student-011', 'class-b', 'active', datetime('now')),
('enroll-012', 'student-012', 'class-b', 'active', datetime('now')),
('enroll-013', 'student-013', 'class-b-half', 'active', datetime('now')),
('enroll-014', 'student-014', 'class-b', 'active', datetime('now')),
('enroll-015', 'student-015', 'class-b', 'active', datetime('now')),
('enroll-016', 'student-016', 'class-b', 'active', datetime('now')),
('enroll-017', 'student-017', 'class-b-half', 'active', datetime('now')),
('enroll-018', 'student-018', 'class-b-half', 'active', datetime('now')),
('enroll-019', 'student-019', 'class-d', 'active', datetime('now')),
('enroll-020', 'student-020', 'class-b', 'active', datetime('now')),
('enroll-021', 'student-021', 'class-b', 'active', datetime('now')),
('enroll-022', 'student-022', 'class-b-half', 'active', datetime('now')),
('enroll-023', 'student-023', 'class-b', 'active', datetime('now')),
('enroll-024', 'student-024', 'class-b-half', 'active', datetime('now')),
('enroll-025', 'student-025', 'class-a', 'active', datetime('now')),
('enroll-026', 'student-026', 'class-a', 'active', datetime('now')),
('enroll-027', 'student-027', 'class-b', 'active', datetime('now')),
('enroll-028', 'student-028', 'class-b', 'active', datetime('now')),
('enroll-029', 'student-029', 'class-b', 'active', datetime('now')),
('enroll-030', 'student-030', 'class-b', 'active', datetime('now'));

-- Insert payment records with calculated totals
INSERT INTO payments (id, user_id, amount, status, payment_method, transaction_ref, due_date, paid_date, proof_url, recorded_by, notes, created_at, updated_at) VALUES
('payment-001', 'student-001', 1200000, 'paid', 'cash', NULL, datetime('now'), datetime('now'), NULL, 'admin', 'Payment from handwritten records. Class: B2. Total: KES 12,000', datetime('now'), datetime('now')),
('payment-002', 'student-002', 500000, 'paid', 'cash', NULL, datetime('now'), datetime('now'), NULL, 'admin', 'Payment from handwritten records. Class: B2. Total: KES 5,000', datetime('now'), datetime('now')),
('payment-003', 'student-003', 975000, 'paid', 'cash', NULL, datetime('now'), datetime('now'), NULL, 'admin', 'Payment from handwritten records. Class: B2. Total: KES 9,750', datetime('now'), datetime('now')),
('payment-004', 'student-004', 600000, 'paid', 'cash', NULL, datetime('now'), datetime('now'), NULL, 'admin', 'Payment from handwritten records. Class: B2. Total: KES 6,000', datetime('now'), datetime('now')),
('payment-005', 'student-005', 300000, 'paid', 'cash', NULL, datetime('now'), datetime('now'), NULL, 'admin', 'Payment from handwritten records. Class: B2. Total: KES 3,000', datetime('now'), datetime('now')),
('payment-006', 'student-006', 1210000, 'paid', 'cash', NULL, datetime('now'), datetime('now'), NULL, 'admin', 'Payment from handwritten records. Class: A. Total: KES 12,100', datetime('now'), datetime('now')),
('payment-007', 'student-007', 500000, 'paid', 'cash', NULL, datetime('now'), datetime('now'), NULL, 'admin', 'Payment from handwritten records. Class: B. Total: KES 5,000', datetime('now'), datetime('now')),
('payment-008', 'student-008', 1150000, 'paid', 'cash', NULL, datetime('now'), datetime('now'), NULL, 'admin', 'Payment from handwritten records. Class: B2. Total: KES 11,500', datetime('now'), datetime('now')),
('payment-009', 'student-009', 200000, 'paid', 'cash', NULL, datetime('now'), datetime('now'), NULL, 'admin', 'Payment from handwritten records. Class: B½. Total: KES 2,000', datetime('now'), datetime('now')),
('payment-010', 'student-010', 875000, 'paid', 'cash', NULL, datetime('now'), datetime('now'), NULL, 'admin', 'Payment from handwritten records. Class: B½. Total: KES 8,750', datetime('now'), datetime('now')),
('payment-011', 'student-011', 500000, 'paid', 'cash', NULL, datetime('now'), datetime('now'), NULL, 'admin', 'Payment from handwritten records. Class: B. Total: KES 5,000', datetime('now'), datetime('now')),
('payment-012', 'student-012', 100000, 'paid', 'cash', NULL, datetime('now'), datetime('now'), NULL, 'admin', 'Payment from handwritten records. Class: B. Total: KES 1,000', datetime('now'), datetime('now')),
('payment-013', 'student-013', 600000, 'paid', 'cash', NULL, datetime('now'), datetime('now'), NULL, 'admin', 'Payment from handwritten records. Class: B½. Total: KES 6,000', datetime('now'), datetime('now')),
('payment-014', 'student-014', 700000, 'paid', 'cash', NULL, datetime('now'), datetime('now'), NULL, 'admin', 'Payment from handwritten records. Class: B. Total: KES 7,000', datetime('now'), datetime('now')),
('payment-015', 'student-015', 4800000, 'paid', 'cash', NULL, datetime('now'), datetime('now'), NULL, 'admin', 'Payment from handwritten records. Total: KES 48,000', datetime('now'), datetime('now')),
('payment-016', 'student-016', 4800000, 'paid', 'cash', NULL, datetime('now'), datetime('now'), NULL, 'admin', 'Payment from handwritten records. Total: KES 48,000', datetime('now'), datetime('now')),
('payment-017', 'student-017', 2860000, 'paid', 'cash', NULL, datetime('now'), datetime('now'), NULL, 'admin', 'Payment from handwritten records. Class: B½. Total: KES 28,600', datetime('now'), datetime('now')),
('payment-018', 'student-018', 130000, 'paid', 'cash', NULL, datetime('now'), datetime('now'), NULL, 'admin', 'Payment from handwritten records. Class: B½. Total: KES 1,300', datetime('now'), datetime('now')),
('payment-019', 'student-019', 2000000, 'paid', 'cash', NULL, datetime('now'), datetime('now'), NULL, 'admin', 'Payment from handwritten records. Class: D. Total: KES 20,000', datetime('now'), datetime('now')),
('payment-020', 'student-020', 985000, 'paid', 'cash', NULL, datetime('now'), datetime('now'), NULL, 'admin', 'Payment from handwritten records. Class: B2. Total: KES 9,850', datetime('now'), datetime('now')),
('payment-021', 'student-021', 500000, 'paid', 'cash', NULL, datetime('now'), datetime('now'), NULL, 'admin', 'Payment from handwritten records. Class: B. Total: KES 5,000', datetime('now'), datetime('now')),
('payment-022', 'student-022', 450000, 'paid', 'cash', NULL, datetime('now'), datetime('now'), NULL, 'admin', 'Payment from handwritten records. Class: B½. Total: KES 4,500', datetime('now'), datetime('now')),
('payment-023', 'student-023', 2000000, 'paid', 'cash', NULL, datetime('now'), datetime('now'), NULL, 'admin', 'Payment from handwritten records. Total: KES 20,000', datetime('now'), datetime('now')),
('payment-024', 'student-024', 100000, 'paid', 'cash', NULL, datetime('now'), datetime('now'), NULL, 'admin', 'Payment from handwritten records. Class: B½. Total: KES 1,000', datetime('now'), datetime('now')),
('payment-025', 'student-025', 250000, 'paid', 'cash', NULL, datetime('now'), datetime('now'), NULL, 'admin', 'Payment from handwritten records. Class: A2. Total: KES 2,500', datetime('now'), datetime('now')),
('payment-026', 'student-026', 530000, 'paid', 'cash', NULL, datetime('now'), datetime('now'), NULL, 'admin', 'Payment from handwritten records. Class: A2. Total: KES 5,300', datetime('now'), datetime('now')),
('payment-027', 'student-027', 90000, 'paid', 'cash', NULL, datetime('now'), datetime('now'), NULL, 'admin', 'Payment from handwritten records. Class: B2. Total: KES 900', datetime('now'), datetime('now')),
('payment-028', 'student-028', 100000, 'paid', 'cash', NULL, datetime('now'), datetime('now'), NULL, 'admin', 'Payment from handwritten records. Total: KES 1,000', datetime('now'), datetime('now')),
('payment-029', 'student-029', 200000, 'paid', 'cash', NULL, datetime('now'), datetime('now'), NULL, 'admin', 'Payment from handwritten records. Total: KES 2,000', datetime('now'), datetime('now')),
('payment-030', 'student-030', 600000, 'paid', 'cash', NULL, datetime('now'), datetime('now'), NULL, 'admin', 'Payment from handwritten records. Total: KES 6,000', datetime('now'), datetime('now'));

-- Summary of payments
SELECT 
    'PAYMENT SUMMARY' as summary,
    COUNT(*) as total_students,
    SUM(amount) / 100 as total_amount_kes,
    AVG(amount) / 100 as average_payment_kes
FROM payments 
WHERE notes LIKE '%handwritten records%';